(function(){'use strict';
const COINGECKO='https://api.coingecko.com/api/v3';
const DEX='https://api.dexscreener.com';
const KEY='hunter-pocket-v4';
const CHAINS=['solana','robinhood','base','ethereum','bsc','arbitrum'];
const CHAIN_LABEL={solana:'Solana',robinhood:'Robinhood',base:'Base',ethereum:'Ethereum',bsc:'BSC',arbitrum:'Arbitrum'};
const BLOCKSCOUT={robinhood:'https://robinhoodchain.blockscout.com',base:'https://base.blockscout.com',ethereum:'https://eth.blockscout.com',arbitrum:'https://arbitrum.blockscout.com'};
const RISK={safe:{entry:82,max:2,sl:-.055,tp:.09,size:.12,label:'Prudent'},balanced:{entry:74,max:4,sl:-.085,tp:.16,size:.16,label:'Équilibré'},aggressive:{entry:66,max:6,sl:-.13,tp:.28,size:.22,label:'Agressif'}};
let mem={};
const sget=k=>{try{return localStorage.getItem(k)}catch(e){return mem[k]||null}},sset=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){mem[k]=v}};
const fresh=()=>({marketFilter:'all',chainFilter:CHAINS.slice(),selected:null,bots:[{id:'bot-'+Date.now(),name:'Hunter Balanced',capital:100,cash:100,risk:'balanced',universe:'all',chains:['solana','robinhood','base','ethereum'],whitelist:[],active:false,positions:{},trades:0,log:[]}],wallets:[]});
let state;try{state=JSON.parse(sget(KEY)||'null')}catch(e){}if(!state)state=fresh();
let cg=[],dex=[],news=[],liveCG=false,liveDex=false,busy=false,toastTimer=null;
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),save=()=>sset(KEY,JSON.stringify(state));
const euro=n=>(Number(n)||0).toLocaleString('fr-BE',{style:'currency',currency:'EUR',minimumFractionDigits:2,maximumFractionDigits:2});
const compact=n=>{n=Number(n)||0;return Intl.NumberFormat('fr-BE',{notation:'compact',maximumFractionDigits:1}).format(n)};
const pct=n=>(n>=0?'+':'')+(Number(n)||0).toFixed(2)+' %';
const fmt=n=>{n=Number(n)||0;if(n>=1000)return n.toLocaleString('fr-BE',{style:'currency',currency:'EUR',maximumFractionDigits:0});if(n>=1)return n.toLocaleString('fr-BE',{style:'currency',currency:'EUR',minimumFractionDigits:2,maximumFractionDigits:2});return n.toLocaleString('fr-BE',{style:'currency',currency:'EUR',minimumFractionDigits:n<.01?6:3,maximumFractionDigits:n<.01?8:4});};
function toast(t){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1600)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function sparkSvg(values,w=80,h=36){if(!Array.isArray(values)||values.length<2)return '';let sample=values.length>60?values.filter((_,i)=>i%Math.ceil(values.length/60)===0):values,min=Math.min(...sample),max=Math.max(...sample),range=Math.max(max-min,1e-12),pts=sample.map((v,i)=>`${(2+i*(w-4)/(sample.length-1)).toFixed(1)},${(h-2-(v-min)*(h-4)/range).toFixed(1)}`).join(' '),col=sample.at(-1)>=sample[0]?'#22da7d':'#ff6476';return `<polyline points="${pts}" fill="none" stroke="${col}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>`;}
function normalizeCg(x){let cats=(x.name+' '+x.symbol).toLowerCase();let meme=/doge|shib|pepe|bonk|floki|wif|meme|inu|cat|frog|brett|mog|popcat/.test(cats);return{key:'cg:'+x.id,source:'cg',id:x.id,symbol:(x.symbol||'').toUpperCase(),name:x.name||x.symbol,chain:'multi',kind:meme?'meme':'major',priceEur:+x.current_price||0,priceUsd:null,change24:+x.price_change_percentage_24h||0,change1h:+x.price_change_percentage_1h_in_currency||0,change7d:+x.price_change_percentage_7d_in_currency||0,volume24:+x.total_volume||0,liquidity:null,marketCap:+x.market_cap||0,fdv:+x.fully_diluted_valuation||0,spark:(x.sparkline_in_7d&&x.sparkline_in_7d.price)||[],boost:0,socials:[],pairAgeH:999,buys:0,sells:0,url:'https://www.coingecko.com/en/coins/'+x.id};}
function normalizeDex(pair,boost){let b=pair.baseToken||{},pc=pair.priceChange||{},vol=pair.volume||{},liq=pair.liquidity||{},tx=pair.txns||{},h1=tx.h1||{},created=pair.pairCreatedAt?Math.max(0,(Date.now()-pair.pairCreatedAt)/3600000):999,info=pair.info||{};return{key:'dex:'+pair.chainId+':'+(b.address||pair.pairAddress),source:'dex',id:b.address||pair.pairAddress,symbol:(b.symbol||'???').toUpperCase(),name:b.name||b.symbol||'Token',chain:pair.chainId||'unknown',kind:'meme',priceEur:(+pair.priceUsd||0)*.85,priceUsd:+pair.priceUsd||0,change24:+pc.h24||0,change1h:+pc.h1||0,change5m:+pc.m5||0,change6h:+pc.h6||0,volume24:+vol.h24||0,volume1h:+vol.h1||0,liquidity:+liq.usd||0,marketCap:+pair.marketCap||0,fdv:+pair.fdv||0,spark:[],boost:+(boost&&boost.totalAmount)||0,socials:[...(info.socials||[]),...(boost&&boost.links||[])],pairAgeH:created,buys:+h1.buys||0,sells:+h1.sells||0,url:pair.url||boost?.url||'',pairAddress:pair.pairAddress||'',tokenAddress:b.address||''};}
function score(a){let s=50;s+=clamp((a.change1h||0)*2.2,-16,18);s+=clamp((a.change24||0)*.35,-12,14);if(a.source==='dex'){let liq=a.liquidity||0,vol=a.volume24||0;s+=liq>=100000?12:liq>=30000?8:liq>=10000?4:-14;s+=vol>=500000?12:vol>=100000?8:vol>=25000?4:-7;let tx=(a.buys||0)+(a.sells||0);s+=tx>=250?8:tx>=80?5:tx>=20?2:-2;let ratio=(a.buys+1)/(a.sells+1);s+=ratio>1.35?5:ratio<.7?-5:1;s+=Math.min(8,Math.log10(1+(a.boost||0))*2.4);s+=Math.min(5,(a.socials||[]).length*1.3);if(a.pairAgeH<.25)s-=14;else if(a.pairAgeH<1)s-=7;if(Math.abs(a.change5m||0)>45)s-=12;if(liq>0&&a.fdv>liq*500)s-=8;}else{s+=(a.marketCap||0)>1e10?10:(a.marketCap||0)>1e9?6:2;s+=(a.volume24||0)>1e9?8:(a.volume24||0)>1e8?5:1;}return Math.round(clamp(s,1,99));}
function riskLabel(a){if(a.source==='cg')return a.kind==='major'?'Modéré':'Élevé';let liq=a.liquidity||0;if(liq<10000||a.pairAgeH<.5)return'Très élevé';if(liq<50000||a.pairAgeH<6)return'Élevé';return'Moyen';}
function combined(){let map=new Map();[...cg,...dex].forEach(a=>{let key=a.source==='cg'?a.symbol:a.chain+':'+a.id;if(!map.has(key))map.set(key,a)});return [...map.values()];}
function filteredAssets(){let arr=combined();if(state.marketFilter==='majors')arr=arr.filter(a=>a.kind==='major');if(state.marketFilter==='memes')arr=arr.filter(a=>a.kind==='meme');return arr.sort((a,b)=>score(b)-score(a));}
async function fetchCoinGecko(){try{let r=await fetch(`${COINGECKO}/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=50&page=1&sparkline=true&price_change_percentage=1h,24h,7d`,{cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json();cg=d.map(normalizeCg);liveCG=true}catch(e){if(!cg.length){cg=[{id:'bitcoin',symbol:'btc',name:'Bitcoin',current_price:60000,price_change_percentage_24h:0,total_volume:0,market_cap:1e12,sparkline_in_7d:{price:Array.from({length:80},(_,i)=>60000*(1+Math.sin(i/9)*.018))}},{id:'solana',symbol:'sol',name:'Solana',current_price:150,price_change_percentage_24h:0,total_volume:0,market_cap:8e10,sparkline_in_7d:{price:Array.from({length:80},(_,i)=>150*(1+Math.sin(i/7)*.03))}}].map(normalizeCg)}liveCG=false;}}
async function fetchDex(){try{let r=await fetch(`${DEX}/token-boosts/top/v1`,{cache:'no-store'});if(!r.ok)throw Error(r.status);let boosts=await r.json();boosts=(boosts||[]).filter(x=>CHAINS.includes(x.chainId)).slice(0,45);let groups={};boosts.forEach(b=>(groups[b.chainId]||(groups[b.chainId]=[])).push(b));let pairs=[];for(const chain of Object.keys(groups)){let addrs=groups[chain].map(x=>x.tokenAddress).slice(0,30);if(!addrs.length)continue;try{let pr=await fetch(`${DEX}/tokens/v1/${encodeURIComponent(chain)}/${addrs.map(encodeURIComponent).join(',')}`,{cache:'no-store'});if(pr.ok){let pd=await pr.json();(pd||[]).forEach(p=>{let bo=groups[chain].find(b=>(b.tokenAddress||'').toLowerCase()===(p.baseToken?.address||'').toLowerCase());pairs.push(normalizeDex(p,bo));});}}catch(e){}}let best=new Map();pairs.forEach(p=>{let k=p.chain+':'+p.id,old=best.get(k);if(!old||p.liquidity>old.liquidity)best.set(k,p)});dex=[...best.values()].sort((a,b)=>score(b)-score(a));liveDex=dex.length>0}catch(e){liveDex=false;}}
async function searchDex(q){q=(q||'').trim();if(!q)return;try{let r=await fetch(`${DEX}/latest/dex/search?q=${encodeURIComponent(q)}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json(),pairs=(d.pairs||[]).filter(p=>CHAINS.includes(p.chainId)).slice(0,35).map(p=>normalizeDex(p,null));dex=[...pairs,...dex.filter(x=>!pairs.some(p=>p.chain===x.chain&&p.id===x.id))].slice(0,100);liveDex=true;render()}catch(e){toast('Recherche DexScreener indisponible')}}
async function fetchNews(){try{let query=encodeURIComponent('(bitcoin OR solana OR ethereum OR memecoin OR crypto)');let r=await fetch(`https://api.gdeltproject.org/api/v2/doc/doc?query=${query}&mode=ArtList&maxrecords=25&format=json&sort=HybridRel`,{cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json();news=(d.articles||[]).slice(0,20)}catch(e){news=[]}}
function newsSent(t){t=(t||'').toLowerCase();let pos=['surge','rally','record','launch','approval','adoption','gain','bull','partnership','expands'],neg=['hack','exploit','lawsuit','ban','crash','fraud','scam','liquidation','down','attack'];let s=pos.filter(x=>t.includes(x)).length-neg.filter(x=>t.includes(x)).length;return s>0?'Positif':s<0?'Négatif':'Neutre'}
function detailHtml(a){let sp=a.spark?.length?a.spark:Array.from({length:60},(_,i)=>a.priceEur*(1+Math.sin(i/7)*.01));return `<div class="detail-top"><div class="coin-wrap"><div class="coin ${a.kind==='meme'?'spec':''}">${esc(a.symbol.slice(0,4))}</div><div><div class="sym">${esc(a.symbol)} <span class="chain-tag">${esc(CHAIN_LABEL[a.chain]||a.chain)}</span></div><div class="name">${esc(a.name)}</div></div></div><div class="detail-price"><b>${fmt(a.priceEur)}</b><span class="${a.change24>=0?'up':'down'}">${pct(a.change24)}</span></div></div><div class="chart-box"><svg viewBox="0 0 360 145" preserveAspectRatio="none">${sparkSvg(sp,360,145)}</svg></div><div class="chart-labels"><span>${a.source==='dex'?'DEX pair':'7 jours'}</span><span>Score Hunter ${score(a)}/100</span></div><div class="score-strip"><div><span>Risque</span><b>${riskLabel(a)}</b></div><div><span>Volume 24h</span><b>${compact(a.volume24||0)}</b></div><div><span>Liquidité</span><b>${a.liquidity?('$'+compact(a.liquidity)):'—'}</b></div><div><span>Social heat</span><b>${a.source==='dex'?((a.boost||0)+(a.socials?.length||0)*10):'—'}</b></div></div>`}
function marketRow(a){let sp=a.spark?.length?a.spark.slice(-55):[a.priceEur*.99,a.priceEur,a.priceEur*1.01];return `<div class="market-row" data-key="${esc(a.key)}"><div class="coin-wrap"><div class="coin ${a.kind==='meme'?'spec':''}">${esc(a.symbol.slice(0,3))}</div><div><div class="sym">${esc(a.symbol)} ${a.chain!=='multi'?`<span class="chain-tag">${esc(CHAIN_LABEL[a.chain]||a.chain)}</span>`:''}</div><div class="name">${esc(a.name)}</div></div></div><div><div class="price">${fmt(a.priceEur)}</div><div class="change ${a.change24>=0?'up':'down'}">${pct(a.change24)}</div><div class="score">Hunter ${score(a)}/100</div></div><div class="mini-chart"><svg viewBox="0 0 80 36" preserveAspectRatio="none">${sparkSvg(sp,80,36)}</svg></div></div>`}
function findByKey(k){return combined().find(a=>a.key===k)||combined()[0]}
function bindRows(){document.querySelectorAll('[data-key]').forEach(el=>el.onclick=()=>{state.selected=el.dataset.key;save();renderFeatured()})}
function renderFeatured(){let arr=filteredAssets(),a=findByKey(state.selected)||arr[0];if(!a){$('featuredAsset').innerHTML='<div class="empty"><b>Aucun actif</b><p>Actualise le marché.</p></div>';return}state.selected=a.key;$('featuredAsset').innerHTML=detailHtml(a)}
function renderDashboard(){let arr=filteredAssets().slice(0,18);$('marketList').innerHTML=arr.map(marketRow).join('')||'<div class="empty"><b>Aucun actif</b></div>';renderFeatured();let hot=combined().filter(a=>score(a)>=70).sort((a,b)=>score(b)-score(a)).slice(0,6);$('hotSignals').innerHTML=hot.map((a,i)=>`<div class="signal-card"><span class="rank">#${i+1} · ${esc(CHAIN_LABEL[a.chain]||a.chain)}</span><h3>${esc(a.symbol)} · ${esc(a.name)}</h3><p>${a.source==='dex'?`Liq $${compact(a.liquidity)} · Vol $${compact(a.volume24)} · ${a.buys}/${a.sells} buys/sells (1h)`:`Vol ${compact(a.volume24)} · variation 24h ${pct(a.change24)}`}</p><div class="signal-score">${score(a)}</div></div>`).join('')||'<div class="empty"><b>Pas de signal fort</b><p>Le scanner attend davantage de données.</p></div>';bindRows();}
function renderScanner(){let arr=dex.filter(a=>state.chainFilter.includes(a.chain)).sort((a,b)=>score(b)-score(a));$('dexList').innerHTML=arr.map(marketRow).join('')||'<div class="empty"><b>Aucun token détecté</b><p>Appuie sur Scanner ou change de chaîne.</p></div>';bindRows()}
function aggregate(){let cash=0,eq=0,pos=0,active=0,cap=0;state.bots.forEach(b=>{cap+=b.capital;cash+=b.cash;eq+=botEquity(b);pos+=Object.keys(b.positions||{}).length;if(b.active)active++});return{cash,eq,pos,active,cap,exposure:eq-cash}}
function botAssetUniverse(bot){let arr=combined().filter(a=>a.priceEur>0);if(bot.universe==='majors')arr=arr.filter(a=>a.kind==='major');if(bot.universe==='memes')arr=arr.filter(a=>a.kind==='meme');if(bot.chains?.length)arr=arr.filter(a=>a.chain==='multi'||bot.chains.includes(a.chain));if(bot.whitelist?.length)arr=arr.filter(a=>bot.whitelist.includes(a.symbol.toUpperCase()));return arr}
function botEquity(bot){let ex=Object.values(bot.positions||{}).reduce((s,p)=>{let a=combined().find(x=>x.key===p.key),pr=a?.priceEur||p.entry;return s+p.qty*pr},0);return bot.cash+ex}
function botBuy(bot,a){let cfg=RISK[bot.risk],n=Object.keys(bot.positions||{}).length;if(n>=cfg.max||bot.positions[a.key])return;let amount=Math.min(bot.cash,Math.max(5,bot.capital*cfg.size));if(amount<5)return;let fee=amount*.001,qty=(amount-fee)/a.priceEur;bot.cash-=amount;bot.positions[a.key]={key:a.key,symbol:a.symbol,name:a.name,entry:a.priceEur,qty,cost:amount,sl:cfg.sl,tp:cfg.tp};bot.trades++;bot.log.unshift({t:Date.now(),m:`BUY ${a.symbol} ${euro(amount)} · score ${score(a)}`})}
function botSell(bot,key,reason){let p=bot.positions[key];if(!p)return;let a=combined().find(x=>x.key===key),pr=a?.priceEur||p.entry,val=p.qty*pr*.999,pnl=val-p.cost;bot.cash+=val;delete bot.positions[key];bot.trades++;bot.log.unshift({t:Date.now(),m:`SELL ${p.symbol} ${reason} · ${pnl>=0?'+':''}${euro(pnl)}`})}
function evaluateBot(bot){if(!bot.active)return;let cfg=RISK[bot.risk];Object.values({...bot.positions}).forEach(p=>{let a=combined().find(x=>x.key===p.key);if(!a)return;let ret=a.priceEur/p.entry-1;if(ret<=p.sl)botSell(bot,p.key,'STOP '+pct(ret*100));else if(ret>=p.tp)botSell(bot,p.key,'TP '+pct(ret*100));else if(score(a)<42)botSell(bot,p.key,'SCORE '+score(a))});let ranked=botAssetUniverse(bot).sort((a,b)=>score(b)-score(a));for(let a of ranked){if(Object.keys(bot.positions).length>=cfg.max)break;if(score(a)>=cfg.entry&&!bot.positions[a.key])botBuy(bot,a)}save()}
function renderBots(){if(!state.bots.length){$('botsList').innerHTML='<div class="empty"><b>Aucun bot</b><p>Crée une stratégie pour commencer.</p></div>';return}$('botsList').innerHTML=state.bots.map(b=>{let eq=botEquity(b),pnl=eq-b.capital,positions=Object.values(b.positions||{});return `<div class="bot-card"><div class="row"><div><h3>${esc(b.name)}</h3><div class="muted">${RISK[b.risk].label} · ${esc(b.universe)} · ${(b.chains||[]).map(c=>CHAIN_LABEL[c]||c).join(', ')||'toutes chaînes'}${b.whitelist?.length?' · '+b.whitelist.join(', '):''}</div></div><span class="bot-state ${b.active?'on':''}">${b.active?'ACTIF':'ARRÊTÉ'}</span></div><div class="bot-metrics"><div><span>Equity</span><b>${euro(eq)}</b></div><div><span>P&L</span><b class="${pnl>=0?'up':'down'}">${pnl>=0?'+':''}${euro(pnl)}</b></div><div><span>Positions</span><b>${positions.length}</b></div><div><span>Trades</span><b>${b.trades||0}</b></div></div>${positions.slice(0,6).map(p=>{let a=combined().find(x=>x.key===p.key),pr=a?.priceEur||p.entry,ret=(pr/p.entry-1)*100;return `<div class="bot-position"><span>${esc(p.symbol)}</span><b class="${ret>=0?'up':'down'}">${pct(ret)}</b></div>`}).join('')}<div class="bot-actions"><button class="${b.active?'':'start'}" data-bot-toggle="${b.id}">${b.active?'Stop':'Démarrer'}</button><button data-bot-close="${b.id}">Tout clôturer</button><button data-bot-delete="${b.id}">Supprimer</button></div></div>`}).join('');document.querySelectorAll('[data-bot-toggle]').forEach(x=>x.onclick=()=>{let b=state.bots.find(z=>z.id===x.dataset.botToggle);b.active=!b.active;if(b.active)evaluateBot(b);save();render()});document.querySelectorAll('[data-bot-close]').forEach(x=>x.onclick=()=>{let b=state.bots.find(z=>z.id===x.dataset.botClose);Object.keys({...b.positions}).forEach(k=>botSell(b,k,'MANUEL'));save();render()});document.querySelectorAll('[data-bot-delete]').forEach(x=>x.onclick=()=>{state.bots=state.bots.filter(z=>z.id!==x.dataset.botDelete);save();render()})}
function renderNews(){if(!news.length){$('newsList').innerHTML='<div class="empty"><b>Actualités indisponibles</b><p>Le flux GDELT est temporairement vide; les signaux DEX restent actifs.</p></div>';return}$('newsList').innerHTML=news.map(n=>`<div class="news-item"><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a><div class="news-meta">${esc(n.domain||'Source')} · ${esc(n.seendate||'')} <span class="news-sentiment">${newsSent(n.title)}</span></div></div>`).join('')}
async function enrichWallet(w){w.status='loading';renderWallets();try{if(w.chain==='solana'){let r=await fetch('https://api.mainnet-beta.solana.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify([{jsonrpc:'2.0',id:1,method:'getBalance',params:[w.address]},{jsonrpc:'2.0',id:2,method:'getSignaturesForAddress',params:[w.address,{limit:25}]}])});let d=await r.json(),bal=(d[0]?.result?.value||0)/1e9,sigs=d[1]?.result||[];w.balance=bal+' SOL';w.txCount=sigs.length;w.recent=sigs[0]?.blockTime?new Date(sigs[0].blockTime*1000).toLocaleString('fr-BE'):'—';w.score=Math.round(clamp(35+sigs.length*2.3,1,95));w.status='ok'}else{let host=BLOCKSCOUT[w.chain];if(!host)throw Error('Unsupported');let r=await fetch(`${host}/api/v2/addresses/${encodeURIComponent(w.address)}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json();let bal=Number(d.coin_balance||0)/1e18,tx=Number(d.transactions_count||0);w.balance=bal.toFixed(4)+' ETH';w.txCount=tx;w.recent='Index Blockscout';w.score=Math.round(clamp(35+Math.log10(1+tx)*14,1,95));w.status='ok'}}catch(e){w.status='error';w.score=0}save();renderWallets()}
function renderWallets(){if(!state.wallets.length){$('walletList').innerHTML='<div class="empty"><b>Aucun wallet suivi</b><p>Ajoute des adresses publiques Solana ou EVM.</p></div>';return}$('walletList').innerHTML=state.wallets.map(w=>`<div class="watch-wallet"><div class="row"><div><b>${esc(w.name||'Wallet')}</b><div class="wallet-address">${esc(w.address)}</div><div class="muted">${esc(CHAIN_LABEL[w.chain]||w.chain)} · ${w.status==='loading'?'Analyse…':w.status==='error'?'Données indisponibles':`${esc(w.balance||'—')} · activité ${w.txCount||0}`}</div></div><div class="wallet-score">${w.score||'—'}</div></div><div class="row" style="margin-top:8px"><span class="muted">Score activité/ancienneté — P&L historique non vérifié sans indexeur swaps.</span><button class="soft-btn" data-wallet-refresh="${w.id}">↻</button></div></div>`).join('');document.querySelectorAll('[data-wallet-refresh]').forEach(x=>x.onclick=()=>{let w=state.wallets.find(z=>z.id===x.dataset.walletRefresh);enrichWallet(w)})}
function renderSocial(){let arr=dex.filter(a=>(a.socials?.length||0)>0).sort((a,b)=>(b.boost||0)-(a.boost||0)).slice(0,30);$('socialList').innerHTML=arr.map(a=>`<div class="market-row"><div class="coin-wrap"><div class="coin spec">${esc(a.symbol.slice(0,3))}</div><div><div class="sym">${esc(a.symbol)} <span class="chain-tag">${esc(CHAIN_LABEL[a.chain]||a.chain)}</span></div><div class="name">${a.socials.length} lien(s) social · boost ${a.boost||0}</div></div></div><div><div class="price">${fmt(a.priceEur)}</div><div class="change ${a.change24>=0?'up':'down'}">${pct(a.change24)}</div><div class="score">Hunter ${score(a)}/100</div></div><div>${a.url?`<a class="soft-btn" href="${esc(a.url)}" target="_blank" rel="noopener">DEX</a>`:''}</div></div>`).join('')||'<div class="empty"><b>Pas de profil social chargé</b></div>'}
function renderIntel(){renderNews();renderWallets();renderSocial()}
function renderChainFilters(){$('chainFilters').innerHTML=CHAINS.map(c=>`<button class="chip ${state.chainFilter.includes(c)?'active':''}" data-chain="${c}">${CHAIN_LABEL[c]}</button>`).join('');document.querySelectorAll('[data-chain]').forEach(x=>x.onclick=()=>{let c=x.dataset.chain;state.chainFilter=state.chainFilter.includes(c)?state.chainFilter.filter(z=>z!==c):[...state.chainFilter,c];save();renderChainFilters();renderScanner()});$('botChainChoices').innerHTML=CHAINS.map(c=>`<button type="button" class="check active" data-botchain="${c}">${CHAIN_LABEL[c]}</button>`).join('');document.querySelectorAll('[data-botchain]').forEach(x=>x.onclick=()=>x.classList.toggle('active'))}
function render(){let ag=aggregate(),pnl=ag.eq-ag.cap,pp=ag.cap?pnl/ag.cap*100:0;$('globalEquity').textContent=euro(ag.eq);$('globalCash').textContent=euro(ag.cash);$('globalExposure').textContent=euro(ag.exposure);$('activeBots').textContent=ag.active;$('positionTotal').textContent=ag.pos;$('globalPnl').textContent=(pnl>=0?'+':'')+euro(pnl)+' ('+pct(pp)+')';$('globalPnl').className='pnl-line '+(pnl>0?'up':pnl<0?'down':'');let live=liveCG||liveDex;$('liveBadge').className='status-badge '+(live?'live':'');$('liveBadge').querySelector('b').textContent=live?'LIVE':'DÉMO';$('marketSource').textContent=`${liveCG?'CoinGecko LIVE':'CoinGecko fallback'} · ${liveDex?'DexScreener LIVE':'DexScreener indisponible'} · ${combined().length} actifs`;renderDashboard();renderScanner();renderBots();renderIntel();save()}
async function refreshAll(){if(busy)return;busy=true;toast('Mise à jour marché…');await Promise.all([fetchCoinGecko(),fetchDex(),fetchNews()]);state.bots.filter(b=>b.active).forEach(evaluateBot);busy=false;render()}
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}
function setup(){document.querySelectorAll('.nav-btn').forEach(x=>x.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(n=>n.classList.remove('active'));x.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(x.dataset.view).classList.add('active')});document.querySelectorAll('[data-marketfilter]').forEach(x=>x.onclick=()=>{state.marketFilter=x.dataset.marketfilter;document.querySelectorAll('[data-marketfilter]').forEach(c=>c.classList.toggle('active',c===x));save();renderDashboard()});document.querySelectorAll('[data-closemodal]').forEach(x=>x.onclick=()=>closeModal(x.dataset.closemodal));document.querySelectorAll('.modal-back').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));$('refreshBtn').onclick=refreshAll;$('reloadDexBtn').onclick=async()=>{await fetchDex();render()};$('searchTokenBtn').onclick=()=>searchDex($('tokenSearch').value);$('tokenSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchDex(e.target.value)});$('newBotBtn').onclick=()=>openModal('botModal');$('createBotBtn').onclick=()=>{let chains=[...document.querySelectorAll('[data-botchain].active')].map(x=>x.dataset.botchain),budget=clamp(Number($('botBudget').value)||100,20,100000),wl=$('botWhitelist').value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);state.bots.push({id:'bot-'+Date.now(),name:$('botName').value.trim()||'Hunter Bot',capital:budget,cash:budget,risk:$('botRisk').value,universe:$('botUniverse').value,chains,whitelist:wl,active:false,positions:{},trades:0,log:[]});save();closeModal('botModal');render();toast('Bot créé')};$('refreshIntelBtn').onclick=async()=>{await Promise.all([fetchNews(),fetchDex()]);renderIntel()};document.querySelectorAll('.intel-tab').forEach(x=>x.onclick=()=>{document.querySelectorAll('.intel-tab').forEach(y=>y.classList.remove('active'));x.classList.add('active');document.querySelectorAll('.intel-panel').forEach(p=>p.classList.remove('active'));$(x.dataset.inteltab+'Panel').classList.add('active')});$('addWalletBtn').onclick=()=>openModal('walletModal');$('saveWalletBtn').onclick=()=>{let address=$('watchWalletAddress').value.trim();if(!address){toast('Adresse requise');return}let w={id:'w-'+Date.now(),name:$('watchWalletName').value.trim()||'Wallet',chain:$('watchWalletChain').value,address,status:'new',score:0};state.wallets.push(w);save();closeModal('walletModal');renderWallets();enrichWallet(w)};$('settingsBtn').onclick=()=>openModal('settingsModal');$('resetAppBtn').onclick=()=>{state=fresh();save();closeModal('settingsModal');renderChainFilters();render();toast('Données réinitialisées')};renderChainFilters();}
setup();fetchCoinGecko().then(()=>{render();return fetchDex()}).then(()=>{render();return fetchNews()}).then(()=>render());setInterval(()=>{state.bots.filter(b=>b.active).forEach(evaluateBot);render()},15000);setInterval(()=>{fetchCoinGecko().then(()=>fetchDex()).then(()=>{state.bots.filter(b=>b.active).forEach(evaluateBot);render()})},60000);
})();